#!/bin/bash

echo "🚀 Delivery Website - Pre-Deployment Checklist"
echo "=============================================="

# Check if required files exist
echo "📁 Checking required files..."
if [ -f "render.yaml" ]; then
    echo "✅ render.yaml found"
else
    echo "❌ render.yaml missing"
fi

if [ -f "backend/requirements.txt" ]; then
    echo "✅ backend/requirements.txt found"
else
    echo "❌ backend/requirements.txt missing"
fi

if [ -f "frontend/package.json" ]; then
    echo "✅ frontend/package.json found"
else
    echo "❌ frontend/package.json missing"
fi

if [ -f ".env.example" ]; then
    echo "✅ .env.example found"
else
    echo "❌ .env.example missing"
fi

echo ""
echo "🔧 Checking backend configuration..."
cd backend
if python3 -c "import fastapi, uvicorn, firebase_admin" 2>/dev/null; then
    echo "✅ Backend dependencies can be imported"
else
    echo "❌ Backend dependencies missing - run: pip install -r requirements.txt"
fi
cd ..

echo ""
echo "🔧 Checking frontend configuration..."
cd frontend
if npm list --depth=0 2>/dev/null | grep -q "vite"; then
    echo "✅ Frontend dependencies installed"
else
    echo "❌ Frontend dependencies missing - run: npm install"
fi
cd ..

echo ""
echo "📝 Environment Variables Check:"
echo "The following environment variables need to be set in Render:"
echo "- VITE_FIREBASE_API_KEY"
echo "- VITE_FIREBASE_AUTH_DOMAIN"
echo "- VITE_FIREBASE_PROJECT_ID"
echo "- VITE_FIREBASE_STORAGE_BUCKET"
echo "- VITE_FIREBASE_MESSAGING_SENDER_ID"
echo "- VITE_FIREBASE_APP_ID"
echo "- VITE_FIREBASE_MEASUREMENT_ID"
echo "- FIREBASE_SERVICE_ACCOUNT_PATH"
echo "- JWT_SECRET (auto-generated by Render)"

echo ""
echo "🌐 Testing local build..."
echo "Testing frontend build..."
cd frontend
if npm run build 2>/dev/null; then
    echo "✅ Frontend builds successfully"
else
    echo "❌ Frontend build failed"
fi
cd ..

echo ""
echo "Testing backend startup..."
cd backend
if python3 -c "from main import app; print('✅ Backend imports successfully')" 2>/dev/null; then
    echo "✅ Backend imports successfully"
else
    echo "❌ Backend has import errors"
fi
cd ..

echo ""
echo "📋 Next Steps:"
echo "1. Set up your environment variables in Render dashboard"
echo "2. Upload your Firebase service account JSON file"
echo "3. Deploy using the render.yaml configuration"
echo "4. Test the deployed application"
echo "5. Update CORS settings for production"

echo ""
echo "🎉 Pre-deployment check complete!"
