services:
  # Combined Frontend + Backend Service
  - type: web
    name: parcel-tracker
    env: python
    plan: free
    buildCommand: cd frontend && npm ci && npm run build && cd ../backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: VITE_API_URL
        value: https://parcel-trackerr.onrender.com
      - key: VITE_FIREBASE_API_KEY
        sync: false
      - key: VITE_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: VITE_FIREBASE_PROJECT_ID
        sync: false
      - key: VITE_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: VITE_FIREBASE_APP_ID
        sync: false
      - key: VITE_FIREBASE_MEASUREMENT_ID
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_PATH
        sync: false
      - key: JWT_SECRET
        generateValue: true
