#!/bin/bash

echo "🔍 Render Deployment Debug Script"
echo "================================="

echo ""
echo "📋 Checking project structure..."
if [ -d "frontend" ]; then
    echo "✅ frontend directory exists"
else
    echo "❌ frontend directory missing"
fi

if [ -d "backend" ]; then
    echo "✅ backend directory exists"
else
    echo "❌ backend directory missing"
fi

if [ -f "render.yaml" ]; then
    echo "✅ render.yaml exists"
else
    echo "❌ render.yaml missing"
fi

echo ""
echo "🔧 Testing frontend build..."
cd frontend
if npm run build > /tmp/build.log 2>&1; then
    echo "✅ Frontend builds successfully"
    if [ -d "dist" ]; then
        echo "✅ dist directory created"
        echo "📁 Build output:"
        ls -la dist/ | head -10
    else
        echo "❌ dist directory not created"
    fi
else
    echo "❌ Frontend build failed"
    echo "📄 Build errors:"
    cat /tmp/build.log
fi
cd ..

echo ""
echo "🔧 Testing backend setup..."
cd backend
if python3 -c "import fastapi, uvicorn, firebase_admin; print('✅ All dependencies available')" 2>/dev/null; then
    echo "✅ Backend dependencies available"
else
    echo "❌ Backend dependencies missing"
    echo "💡 Run: pip install -r requirements.txt"
fi
cd ..

echo ""
echo "📝 Configuration checklist:"
echo "1. [ ] Set VITE_FIREBASE_* environment variables in Render"
echo "2. [ ] Upload Firebase service account JSON file"
echo "3. [ ] Set FIREBASE_SERVICE_ACCOUNT_PATH variable"
echo "4. [ ] Verify JWT_SECRET is auto-generated by Render"
echo "5. [ ] Check CORS configuration in backend/main.py"

echo ""
echo "🌐 Common Render URLs:"
echo "Frontend: https://your-service-name.onrender.com"
echo "Backend: https://your-backend-service.onrender.com"
echo "Health check: curl https://your-backend-service.onrender.com/docs"

echo ""
echo "🔧 If you get 404 errors:"
echo "1. Check if the service is deployed and running in Render dashboard"
echo "2. Verify the build completed successfully"
echo "3. Check environment variables are set correctly"
echo "4. Look at the service logs in Render dashboard"

echo ""
echo "📞 Need help? Check:"
echo "- Render dashboard logs"
echo "- Firebase console for authentication errors"
echo "- Browser developer tools for frontend errors"
