services:
  # Frontend - Static Site
  - type: web
    name: delivery-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: delivery-backend
          property: host
      - key: VITE_FIREBASE_API_KEY
        sync: false
      - key: VITE_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: VITE_FIREBASE_PROJECT_ID
        sync: false
      - key: VITE_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: VITE_FIREBASE_APP_ID
        sync: false
      - key: VITE_FIREBASE_MEASUREMENT_ID
        sync: false

  # Backend - FastAPI Service
  - type: web
    name: delivery-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT_PATH
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PYTHONPATH
        value: /opt/render/project/src
